export { default as About } from "./About"
export { default as Cart } from "./Cart"
export { default as Home } from "./Home"
export { default as NoMatch } from "./NoMatch"
export { default as Products } from "./Products"
export { default as SingleProduct } from "./SingleProduct"
